// export const API_URL = "http://localhost:3001"
export const API_URL = "https://go-problem-test.an.r.appspot.com"
export const HOME = "/"
export const SITE_NAME = "GO-PROBLEM"
export const bonus = 100
export const loginFailCases = ["Not exist email", "Wrong password"]
export const LANGUAGE_IDX = "languageIdx"
export const USERINFO = "userInfo"
export const CREATED = "created"
export const TRIED = "tried"
export const SOLVED = "solved"
export const UNRESOLVED = "unresolved"
export const LIKED = "liked"
export const TRY = "try"
export const SELF = "self"
export const ANSWER = "answer"
export const VARIATIONS = "variations"
export const ANSWERS = "answers"
export const QUESTIONS = "questions"
export const SORTING_IDX = "sortingIdx"
export const PAGE = "page"
export const resolution = 4
export const MARGIN = 1
export const COMMENT = "comment"
export const TURN = "turn"
export const LEVEL = "level"
export const PROBLEM_INDICES = "problemIndices"
export const PROBLEM_INDEX = "problemIndex"
export const mobileFontSize = "80%"
export const languageList = ["ENG", "한국어", "中文", "日本語"]
export const expires = 365 * 24 * 60 * 60 * 1000
export const problemsPerPage = 24
export const messagesPerPage = 10
export const POST = "POST"
export const PATCH = "PATCH"
export const DELETE = "DELETE"
export const TOKEN = "Token"
export const REQUESTS = "requests"

