export const menuWords = {
  chooseColorWarning: ["Please choose color", "색상을 먼저 고르세요", "选择颜色", "色を選択してください"],
  invalidBoardWarning: ["Invalid board", "적합하지 않은 보드입니다", "无效的盘", "無効なボード"],
  commentLengthWarning: ["Write in 50 characters or less", "50자 이내로 작성하세요", "书写内容不超过 50 个字符", "50文字以内で書いてください"],
  boardSize: ["board size", "바둑판 크기", "棋盘大小", "ボードのサイズ"],
  turn: ["turn", "차례", "转动", "順番"],
  black: ["black", "흑", "黑棋", "黒"],
  BLACK: ["BLACK", "흑", "黑棋", "黒"],
  blackTurn: ["BLACK", "흑선", "黑先", "黒先"],
  white: ["white", "백", "白棋", "白"],
  WHITE: ["WHITE", "백", "白棋", "白"],
  whiteTurn: ["WHITE", "백선", "白先", "白先"],
  level: ["level", "레벨", "等级", "レベル"],
  LEVEL: ["LEVEL", "레벨", "等级", "レベル"],
  creator: ["creator", "만든이", "创造者", "クリエイター"],
  CREATOR: ["CREATOR", "만든이", "创造者", "クリエイター"],
  K: ["K", "급", "级", "級"],
  D: ["D", "단", "段", "段"],
  remove: ["remove", "지우기", "消除", "除く"],
  allClear: ["board clear", "바둑판 초기화", "棋盘初始化", "ボードクリア"],
  create: ["create", "만들기", "创造", "作る"],
  invalidResultWarning: ["Invalid result", "적합하지 않은 결과입니다", "无效结果", "無効な結果"],
  saved: ["Saved", "저장되었습니다.", "已保存", "保存されました"],
  invalidConditionWarning: ["Invalid condition", "적합하지 않은 조건입니다", "无效条件", "無効な条件"],
  previous: ["previous", "이전 수", "上一步", "以前"],
  addVariation: ["add variatiton", "실패도 추가하기", "添加失败", "失敗図を追加"],
  addAnswers: ["add answers", "정답도 추가하기", "添加答案", "正解図を追加"],
  updateVariation: ["update variations", "변화도 저장 완료하기", "更新变化", "変化図の保存を完了する"],
  removeVariation: ["remove variation", "변화도 지우기", "删除变化", "変化図削除する"],
  reset: ["reset", "초기화", "初始化", "初期化"],
  result: ["result", "결과", "结果", "結果"],
  correct: ["correct", "정답", "正确", "正解"],
  wrong: ["wrong", "실패", "错误", "失敗"],
  modify: ["modify", "수정하기", "调整", "修正する"],
  next: ["next", "다음 수", "下一步", "次"],
  noComment: ["No comment", "코멘트 없음", "没有意见", "ノーコメント"],
  noProblemWarning: ["The problem does not exist", "문제가 존재하지 않습니다", "没有问题", "問題は存在しません"],
  modifyProblem: ["modify problem", "문제 수정하기", "修改问题", "問題を修正する"],
  modifyVariations: ["modify variations", "변화도 수정하기", "修改变化", "変化図修正する"],
  try:["try", "도전하기", "尝试", "試みる"],
  practice: ["self mode", "셀프 모드", "自我模式", "セルフモード"],
  previousProblem: ["previous problem", "이전 문제", "上一个问题", "以前の問題"],
  nextProblem: ["next problem", "다음 문제", "下一个问题", "次の問題"],
  returnProblem: ["return problem", "문제로 돌아가기", "退货问题", "問題に戻る"],
  showAnswer: ["see answer", "정답 보기", "查看答案", "正解を見る"],
  like: ["like", "좋아요", "喜欢", "好き"],
  dislike: ["dislike", "싫어요", "不喜欢", "嫌い"],
  hi: ["hi", "반갑습니다", "你好", "こんにちは"],
  login: ["log in", "로그인", "登录", "ログイン"],
  signup: ["sign-up", "가입하기", "报名", "加入する"],
  point: ["point", "포인트", "点", "ポイント"],
  name: ["nickname", "대화명", "昵称", "あだ名"],
  solved: ["solved problem", "해결한 문제", "解决了", "解決済み問題"],
  unresolved: ["unresolved problem", "미해결 문제", "未解決的問題", "未解決の問題"],
  search: ["search", "검색", "搜索", "検索"],
  myPage: ["My page", "마이 페이지", "我的页面", "マイページ"],
  logout: ["Log out", "로그아웃", "退出", "ログアウト"],
  emailWarning: ["Exist same email", "이미 가입된 이메일입니다", "存在相同的电子邮件", "同じ電子メールが存在する"],
  passwordWarning: ["At least 8 characters", "8자 이상 입력해 주세요", "至少 8 个字符", "8文字以上入力してください"],
  repeatPasswordWarning: ["Different with password", "비밀번호와 다릅니다", "与密码不同", "パスワードが異なる"],
  nameWarning: ["Exist same nickname", "이미 가입된 이름입니다.", "存在相同的昵称", "同じニックネームが存在します"],
  problems: ["problems", "문제", "题库", "問題"],
  welcome: ["Welcome", "반갑습니다", "欢迎", "ようこそ"],
  notFoundWarning: ["Wrong address", "잘못된 주소입니다", "网址地址错误", "間違った住所"],
  return: ["return", "돌아가기", "返回", "返却する"],
  duplicateVariationWarning: ["Exist this variation", "이미 존재하는 변화입니다", "存在这种变化", "同じ変化図が存在します"],
  nameFormWarning: ["Space characters are not valid characters", "공백문자는 사용이 불가능합니다", "空格字符不是有效字符", "スペース文字が有効な文字ではありません"],
  eMail: ["e-mail", "이메일", "电子邮件", "電子メール"],
  password: ["password", "비밀번호", "密码", "パスワード"],
  repeatPassword: ["repeat-password", "비밀번호 확인", "重复输入密码", "リピートパスワード"],
  explanation: ["explanation", "설명", "说明", "コメント"],
  language: ["language", "언어", "语言", "言語"],
  pass: ["pass", "패스", "通过", "通過"],
  created: ["created", "나의 창작", "我的创作", "私の創作"],
  comment: ["comment", "댓글", "评论", "コメント"],
  register: ["register", "등록", "登记", "登録"],
  checkAnswer: ["check answer", "정답 확인", "检查答案", "正解を確認"],
  deleteProblem: ["delete problem", "문제 삭제하기", "删除问题", "問題を削除"],
  noAnswerWarning: ["answer has not been registered", "아직 등록된 정답이 없습니다", "答案尚未注册", "正解はまだ登録されていません"],
  views: ["VIEWS", "조회수", "观看次数", "ヒット"],
  correctRate: ["CORRECT RATE", "정답률", "正确率", "正解率"],
  requestVariation: ["request variation", "변화도 요청", "请求变化", "変化図要請"],
  requestsReceived: ["Requests received", "받은 요청들", "收到的请求", "受け取ったリクエスト"],
  complete: ["complete", "수정 완료", "修改完成", "修正完了"],
  incomplete: ["incomplete", "수정 미완료", "修改未完成", "修正未完了"],
  liked: ["liked", "좋아하는 문제", "喜欢的问题", "好きな問題"],
}