export const menuWords = {
  invalidBoardWarning: ["Invalid board", "적합하지 않은 보드입니다", "无效的盘", "無効なボード"],
  commentLengthWarning: ["Write in 50 characters or less", "50자 이내로 작성하세요", "书写内容不超过 50 个字符", "50文字以内で書いてください"],
  boardSize: ["Board size", "바둑판 크기", "棋盘大小", "ボードのサイズ"],
  turn: ["Turn", "차례", "转动", "順番"],
  blackTurn: ["Black", "흑선", "黑先", "黒先"],
  whiteTurn: ["White", "백선", "白先", "白先"],
  level: ["Level", "레벨", "等级", "レベル"],
  creator: ["Creator", "만든이", "创造者", "クリエイター"],
  K: ["K", "급", "级", "級"],
  D: ["D", "단", "段", "段"],
  create: ["Create", "만들기", "制作", "作る"],
  register: ["Register", "등록", "登记", "登録"],
  invalidResultWarning: [
    "This result is not suitable. The outcome should be in the favor of the side that makes the last move.", 
    "이 결과는 적합하지 않습니다! 결과는 마지막 수를 놓은 쪽에게 유리해야 합니다.", 
    "这个结果并不合适。结果应该有利于最后采取行动的一方", 
    "この結果は適切ではありません！結果は最後に着手した方に有利でなければなりません"],
  saved: ["Saved", "저장되었습니다.", "已保存", "保存されました"],
  invalidConditionWarning: ["Invalid condition", "적합하지 않은 조건입니다", "无效条件", "無効な条件"],
  addVariation: ["Add failure case", "실패도 등록", "添加失败", "失敗登録"],
  addAnswers: ["Add answers", "정답도 등록", "添加答案", "正解登録"],
  removeVariation: ["Remove variation", "변화도 삭제", "删除变化", "変化図削除"],
  correct: ["Correct", "정답", "正确", "正解"],
  wrong: ["Wrong", "실패", "错误", "失敗"],
  noProblemWarning: ["The problem does not exist", "문제가 존재하지 않습니다", "没有问题", "問題は存在しません"],
  modifyProblem: ["Modify problem", "문제 수정", "修改问题", "問題を修正"],
  try:["Try", "도전하기", "尝试", "試みる"],
  practice: ["Practice", "놓아보기", "试下", "練習"],
  previousProblem: ["Previous problem", "이전 문제", "上一个问题", "前の問題"],
  nextProblem: ["Next problem", "다음 문제", "下一个问题", "次の問題"],
  returnProblem: ["Return problem", "문제로 돌아가기", "退货问题", "問題に戻る"],
  showAnswer: ["See answer", "정답 보기", "查看答案", "正解を見る"],
  hi: ["Hi", "반갑습니다", "你好", "こんにちは"],
  login: ["Log-in", "로그인", "登录", "ログイン"],
  signup: ["Sign-up", "가입하기", "报名", "加入する"],
  name: ["Nickname", "닉네임", "昵称", "あだ名"],
  solved: ["Solved", "해결한 문제", "解决了", "解決済み問題"],
  unresolved: ["Unsolved", "미해결 문제", "未解決的問題", "未解決の問題"],
  logout: ["Log out", "로그아웃", "退出", "ログアウト"],
  emailWarning: ["Exist same email", "이미 가입된 이메일입니다", "存在相同的电子邮件", "同じ電子メールが存在する"],
  passwordWarning: ["At least 8 characters", "8자 이상 입력해 주세요", "至少 8 个字符", "8文字以上入力してください"],
  repeatPasswordWarning: ["Different with password", "비밀번호와 다릅니다", "与密码不同", "パスワードが異なる"],
  nameWarning: ["Exist same nickname", "이미 가입된 이름입니다.", "存在相同的昵称", "同じニックネームが存在します"],
  problems: ["Problems", "문제", "题库", "問題"],
  welcome: ["Welcome", "반갑습니다", "欢迎", "ようこそ"],
  notFoundWarning: ["Wrong address", "잘못된 주소입니다", "网址地址错误", "間違った住所"],
  return: ["Return", "돌아가기", "返回", "返却する"],
  spaceWarning: ["Space characters are not valid characters", "공백문자는 사용이 불가능합니다", "空格字符不是有效字符", "スペース文字が有効な文字ではありません"],
  eMail: ["e-mail", "이메일", "电子邮件", "電子メール"],
  password: ["Password", "비밀번호", "密码", "パスワード"],
  repeatPassword: ["Repeat-password", "비밀번호 확인", "重复输入密码", "リピートパスワード"],
  explanation: ["Explanation", "설명", "说明", "コメント"],
  language: ["Language", "언어", "语言", "言語"],
  created: ["Created", "나의 창작", "我的创作", "私の創作"],
  comment: ["Comment", "댓글", "评论", "コメント"],
  checkAnswer: ["Check answer", "정답 확인", "检查答案", "正解を確認"],
  deleteProblem: ["Delete problem", "문제 삭제", "删除问题", "問題を削除"],
  noAnswerWarning: ["Answer not registered", "아직 등록된 정답이 없습니다", "答案尚未注册", "正解はまだ登録されていません"],
  views: ["Views", "조회수", "观看次数", "ヒット"],
  correctRate: ["Accuracy", "정답률", "正确率", "正解率"],
  requestVariation: ["Request variation", "변화도 요청", "请求变化", "変化図要請"],
  requestsReceived: ["Requests", "받은 요청들", "收到的请求", "受け取ったリクエスト"],
  liked: ["Liked", "좋아하는 문제", "喜欢的问题", "好きな問題"],
  registered: ["A problem has been registered", "문제가 등록 되었습니다", "已登记问题。", "問題が登録されました"],
  perfect: ["Perfect", "완벽합니다.", "完美的", "完璧"],
  wrongWay: ["Think a little more", "조금 더 생각해 보세요", "再想一点", "もう少し考えてみてください"],
  registeredVariationWarning: ["This variation has already been registered", "이미 등록되어 있는 변화도입니다", "这是已经注册的渐变", "すでに登録されている変更図です"],
  rightWay: ["You are on the right way", "올바른 길로 가고 있습니다", "你走在正确的轨道上", "正しい道を進んでいます"],
  deletedProblemWarning: ["The problem has been deleted", "문제가 삭제 되었습니다", "问题已被删除", "問題が削除されました"],
  requestSuggestion: [
    "This move has not been registered. if you want to request variation of this move please push request variation button.",
    "등록되어 있지 않은 수입니다. 출제자에게 변화도를 요청하시려면 변화도 요청을 눌러주세요.",
    "此手牌未注册。如果您想请求此类变化图，请按请求变化按钮。",
    "この手は登録されていません。この手の変化図を要求したい場合は、変化図要請ボタンを押してください"
  ],
  checkMailWarning: [
    "A verification email has been sent. You can log in after authentication.", 
    "인증 메일이 발송 되었습니다. 인증 후 로그인 가능합니다.", 
    "验证电子邮件已发送。认证后即可登录。", 
    "確認メールが送信されました。認証後ログイン可能となります。"
  ],
  requestWarning: [
    "There are unprocessed requests. Please check on My Page.",
    "처리하지 않은 요청이 있습니다. 마이페이지에서 확인해 주세요.",
    "有未处理的请求。请查看我的页面。",
    "未処理のリクエストがあります。マイページよりご確認ください。"
  ],
  loginWarning: ["Login is required.", "로그인이 필요합니다.", "需要登录。", "ログインが必要です。"],
  confirmRequest: ["Confirm request", "요청 확인", "确认请求", "確認リクエスト"],
  deleteProblemWarning: [
    "Once deleted, it cannot be recovered. Are you sure you want to delete?",
    "삭제하면 복구 할 수 없습니다. 정말 삭제하시겠습니까?",
    "一旦删除，就无法恢复。你确定你要删除？",
    "削除すると回復できません。本当に削除しますか？"
  ],
  confirm: ["Confirm", "확인", "确认", "確認"],
  cancel: ["Cancel", "취소", "取消", "取消"],
  deletedNotice: ["Deleted", "삭제 되었습니다", "已删除", "削除されました"],
  modifiedNotice: ["Modified", "수정 완료", "修改完成", "修正完了"],
  noMailWarning: ["This email is not registered", "등록되지 않은 이메일입니다", "该电子邮件未注册", "このメールは登録されていません"],
  verifyWarning: [
    "Email verification has not been completed. Please complete verification through the verification link sent to your email.", 
    "이메일 인증이 완료되지 않았습니다. 이메일로 발송된 인증링크를 통해 인증을 완료해 주세요.", 
    "电子邮件验证尚未完成。请通过发送至您邮箱的验证链接完成验证。", 
    "メール認証が完了していません。メールに送信された確認リンクを通じて確認を完了してください。"
  ],
  incorrectPasswordWarning: ["Password is incorrect", "비밀번호가 틀렸습니다", "密码不正确", "パスワードが正しくありません"],
  invalidEmailFormWarning: ["Invalid email format", "잘못된 이메일 양식", "电子邮件格式无效", "無効な電子メール形式"],
  verificationCompleteNotice: ["Verification completed", "인증 완료", "验证完成", "認証完了"],
  wrongApproachWarning: ["The wrong approach", "잘못된 접근입니다", "错误的做法", "間違ったアプローチです"],
  sortingMethod: ["Sorting method", "정렬 방식", "排序方法", "仕分け方法"],
  allLevel: ["All levels", "모든 레벨", "所有级别", "すべてのレベル"],
  change: ["Change", "변경하기", "改变", "変更する"],
  setting: ["Setting", "설정", "环境", "設定"],
  autoWord: ["Automatically move to the next question", "자동으로 다음 문제로 이동하기", "自动转到下一个问题", "自動的に次の問題に移動する"],
  excluding: ["Excluding solved", "해결한 문제 제외하기", "排除已解决的问题", "解決した問題を除外する"],
  changePassword: ["Change password", "비밀번호 변경하기", "更改密码", "パスワードを変更する"],
  curPasswordNotice: ["Please enter your current password", "현재 비밀번호를 입력해 주세요", "请输入您当前的密码", "現在のパスワードを入力してください"],
  noEmailWarning: ["This email is not registered", "가입되지 않은 이메일입니다", "该邮箱尚未注册", "このメールは登録されていません"],
  checkPasswordUrlNotice: [
    "A password change link has been sent to the email address you entered. Please check your email.",
    "입력하신 이메일로 비밀번호 변경 링크가 발송되었습니다. 메일을 확인해 주세요.",
    "密码更改链接已发送到您输入的电子邮件地址。请查看你的邮箱。",
    "入力したメールアドレスにパスワード変更リンクが送信されました。メールを確認してください"
  ],
  findPassword: ["Find password", "비밀번호 찾기", "查找密码", "パスワードを探す"],
  delete: ["Del", "삭제", "删除", "削除"],
  message: ["Message", "메시지", "信息", "メッセージ"],
  sender: ["Sender", "발신", "发件人", "送信者"],
  receiver: ["Receiver", "수신", "接受者", "受信者"],
  title: ["Title", "제목", "标题", "タイトル"],
  time: ["Time", "시간", "时间", "時間"],
  goToTheProblem: ["Go to the problem", "문제로 이동", "转到问题所在", "問題に移動"],
  enterVariations: ["Enter variations", "변화도 입력", "输入变化", "変化図入力"],
  searchByCreator: ["Search by creator", "출제자로 검색", "按创作者搜索", "クリエイターで検索"],
  sendMessage: ["Send message", "메시지 보내기", "发信息", "メッセージを送信"],
  send: ["Send", "보내기", "发送", "送信"],
  content: ["Content", "내용", "内容", "内容"],
  sent: ["Sent", "전송 완료", "发送完成", "送信完了"],
  sentMessage: ["Sent", "보낸 메시지", "已发送消息", "送信メッセージ"],
  receivedMessage: ["Received", "받은 메시지", "收到消息", "受信メッセージ"],
  saveInformations: ["Save login information", "로그인 정보 저장하기", "保存登录信息", "ログイン情報を保存する"],
  difficulty: ["Difficulty", "난이도", "难点", "難易度"],
  deletedComment: ["This comment has been deleted.", "삭제된 댓글입니다.", "此评论已被删除。", "削除されたコメントです。"],
  createdProblem: ["Created", "만든 문제", "注册的问题", "登録の問題"],
  newestProblem: ["Newest problems", "최신 문제", "最新问题", "最新の問題"],
  seeAll: ["See all", "모두 보기", "查看全部", "全て見る"],
  like: ["Like", "좋아요", "喜欢", "好き"],
}